import {
  ArchiveBoxIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowTrendingUpIcon,
  ArrowUpRightIcon,
  Bars3Icon,
  BellIcon,
  BoltIcon,
  BookmarkIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChatBubbleBottomCenterTextIcon,
  CheckIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  Cog6ToothIcon,
  CreditCardIcon,
  DocumentIcon,
  EllipsisHorizontalIcon,
  EnvelopeIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  GlobeAltIcon,
  HandThumbUpIcon,
  HomeIcon,
  InboxIcon,
  MagnifyingGlassIcon,
  MapIcon,
  PaperAirplaneIcon,
  PencilIcon,
  PencilSquareIcon,
  PhoneIcon,
  PlayIcon,
  PlusIcon,
  RectangleGroupIcon,
  ShoppingBagIcon,
  Square2StackIcon,
  Squares2X2Icon,
  SquaresPlusIcon,
  TableCellsIcon,
  TrashIcon,
  UserCircleIcon,
  UserIcon,
  UsersIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';

import {
  ArrowRightIcon as ArrowRightSolidIcon,
  CheckIcon as CheckSolidIcon,
  Square2StackIcon as Square2StackSolidIcon,
  StarIcon,
} from '@heroicons/react/24/solid';

export {
  ArrowLeftIcon as AngleLeftIcon,
  ArrowRightIcon as AngleRightIcon,
  ArrowDownIcon,
  ArrowPathIcon as ArrowRepeatIcon,
  ArrowRightSolidIcon,
  ArrowTrendingUpIcon as ArrowUpIcon,
  ArrowUpRightIcon,
  Bars3Icon as BarsIcon,
  BellIcon,
  BookmarkIcon,
  Squares2X2Icon as BoxCubeIcon,
  ArchiveBoxIcon as BoxIcon,
  InboxIcon as BoxIconLine,
  CalendarDaysIcon as CalendarIcon,
  CalendarDaysIcon as CalenderIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChatBubbleBottomCenterTextIcon as ChatIcon,
  CheckIcon,
  CheckSolidIcon,
  Square2StackIcon as CheckSquareIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  Cog6ToothIcon as CogIcon,
  CreditCardIcon,
  EnvelopeIcon,
  ExclamationTriangleIcon,
  EyeSlashIcon as EyeCloseIcon,
  EyeIcon,
  PencilSquareIcon as FileEditIcon,
  GlobeAltIcon as GlobeIcon,
  Squares2X2Icon as GridIcon,
  RectangleGroupIcon as GroupIcon,
  HomeIcon,
  EllipsisHorizontalIcon as HorizontaLDots,
  SquaresPlusIcon as LayoutIcon,
  Bars3Icon as ListIcon,
  MagnifyingGlassIcon,
  MapIcon as MapPinIcon,
  EllipsisHorizontalIcon as MoreDotIcon,
  PlayIcon as MusicIcon,
  DocumentIcon as PageIcon,
  PaperAirplaneIcon,
  PencilIcon,
  PhoneIcon,
  ChartPieIcon as PieChartIcon,
  BoltIcon as PlugInIcon,
  PlusIcon,
  ShoppingBagIcon as ShoppingCartIcon,
  Square2StackSolidIcon as SquareIcon,
  Squares2X2Icon as SquaresIcon,
  StarIcon,
  TableCellsIcon as TableIcon,
  HandThumbUpIcon as ThumbUpIcon,
  ClockIcon as TimeIcon,
  TrashIcon,
  UserCircleIcon,
  UserIcon,
  UsersIcon,
  XMarkIcon as XIcon,
};
